export const SET_PRODETAIL_INFO = "SET_PRODETAIL_INFO";
export const SET_PRODETAIL_DIALOG_PARAMS = "SET_PRODETAIL_DIALOG_PARAMS";
export const SET_STAKE_AMOUNT = "SET_STAKE_AMOUNT";
export const SET_PROJECT_INFO = "SET_PROJECT_INFO";
export const SET_REST_STAKE_AMOUNT = "SET_REST_STAKE_AMOUNT";
export const SET_STAKE_MY_AMOUNT = "SET_STAKE_MY_AMOUNT";
export const SET_PAY_STATE = "SET_PAY_STATE";
